import { SlashCommandBuilder } from 'discord.js';

const roasts = [
  "{user} has the gaming skills of a disconnected controller.",
  "I've seen bots with more personality than {user}.",
  "{user}'s internet connection has more drops than their K/D.",
  "If {user} was a game, they'd be in the bargain bin. On clearance. Still not selling.",
  "{user} is the reason games have an easy mode.",
  "The best part of playing with {user} is when they go AFK.",
  "{user} brings the whole squad's average down just by being online.",
  "{user}'s aim is so bad they couldn't hit the ground if they fell.",
  "I'd say {user} is washed, but that implies they were clean at some point.",
  "{user} peaked in the tutorial.",
  "Matchmaking puts {user} on the enemy team as a handicap.",
  "{user} is proof that participation trophies have gone too far.",
  "If {user}'s gameplay was a movie, it'd be rated F for Fraudulent.",
  "{user} rage-quits life decisions the same way they rage-quit ranked.",
  "Even the NPCs talk trash about {user}.",
  "{user} plays like they're using a steering wheel as a controller.",
  "The only carry {user} has ever done is carrying the enemy team to victory.",
  "{user} couldn't clutch a grocery bag.",
  "I've seen better plays from someone's cat walking across a keyboard than from {user}.",
  "{user} is the human equivalent of a lag spike.",
  "When {user} joins the lobby, the enemy team starts celebrating.",
  "{user}'s highlight reel is just a compilation of death cams.",
  "Uninstalling would be the biggest contribution {user} could make to the team.",
  "{user} has a 1:1 ratio of games played to friends lost.",
  "{user}'s strategy guide is just a single page that says 'die'.",
  "If {user} had a dollar for every bad play, they could afford a coach. They'd need one.",
  "{user} thinks 'GG EZ' stands for 'Got Gutted, Entirely Zeroed'.",
  "The only thing {user} is grinding is everyone else's patience.",
  "{user} couldn't even carry a conversation, let alone a game.",
  "I asked AI to predict {user}'s win rate and it just sent back a crying emoji.",
  "{user}'s reaction time is measured in business days.",
  "They should name a difficulty setting after {user}. Below easy.",
  "{user}'s callouts are just screaming and the sound of dying.",
  "The hardest boss {user} ever beat was the CAPTCHA to log in.",
  "Even auto-aim gave up on {user}.",

  // Round 2
  "{user} is the reason the mute button exists.",
  "If {user} was a weapon skin, they'd be default. Forever.",
  "{user}'s game sense is like a sixth sense, except all six are missing.",
  "The only time {user} gets kills is in the killcam — their own.",
  "{user} moves like they're playing on a microwave.",
  "Scientists are studying {user}'s gameplay to understand what true failure looks like.",
  "{user}'s rank is so low it doesn't even have a name. Just a sad face.",
  "When {user} picks up a sniper, the scope files a restraining order.",
  "{user} has been hardstuck since birth.",
  "{user}'s gaming chair does all the heavy lifting. And it's still not enough.",
  "I've seen loading screens contribute more to a team than {user}.",
  "{user} doesn't need a nerf. Nature already handled that.",
  "If {user} was a power-up, they'd be the one that makes you slower.",
  "{user}'s crosshair and the enemy have a long-distance relationship. They never meet.",
  "Adding {user} to the squad is like adding a screen door to a submarine.",
  "{user} has the decision-making skills of a random number generator. A bad one.",
  "{user} is speedrunning the leaderboard. From the bottom.",
  "The tutorial NPC has a higher win rate than {user}.",
  "If cluelessness was a rank, {user} would finally be top 1.",
  "{user} is the living embodiment of 'it's just a game bro' because they certainly aren't playing it.",
  "Friendly fire was invented because of people like {user}.",
  "{user}'s mouse pad has more game sense.",
  "When {user} streams, Twitch asks them to stop.",
  "{user} plays like their monitor is off. And honestly? It might be.",
  "I'd tell {user} to go back to Minecraft, but even the creepers would avoid them.",
  "{user}'s gaming setup cost more than their total lifetime damage output.",
  "The server ping is higher than {user}'s IQ in-game.",
  "If losing was an art, {user} would be Picasso.",
  "{user} makes the practice bots feel good about themselves.",
  "Every time {user} queues up, matchmaking sends a formal apology to their teammates.",
  "{user} is the plot twist nobody wanted on the team.",
  "{user}'s loadout choices are a cry for help.",
  "Watching {user} play is like watching someone try to parallel park... forever.",
  "{user} is so bad, the game offered them a refund. Out of pity.",
  "{user}'s KDA looks like a phone number. For a suicide hotline.",

  // Round 3
  "{user} types 'gg' at the start of the match because they already know.",
  "{user}'s gameplay could be used as a sleep aid.",
  "If {user} was a loot drop, nobody would pick them up.",
  "The only thing {user} has ever carried is disappointment.",
  "Spectating {user} should count as a horror game.",
  "{user} has the map awareness of a blindfolded roomba.",
  "{user}'s voice comms are just heavy breathing and excuses.",
  "Even the afk timer respects {user} more than their teammates do.",
  "{user} brings a butter knife to a gunfight. Metaphorically and somehow literally.",
  "When {user} said they'd clutch it, even their own team started spectating the enemy.",
  "{user} is the reason developers add surrender buttons.",
  "If {user} was an ability, they'd be on a 5-year cooldown and still not worth using.",
  "{user}'s stats are a humanitarian crisis.",
  "{user} makes copper lobbies look like pro league.",
  "The only 360 {user} has ever done is turning their life around. Just kidding, they can't do that either.",
  "{user} plays like their keybinds are in Braille. And they can see.",
  "If you look up 'bot' in the dictionary, there's a screenshot of {user}'s gameplay.",
  "A coin flip has better odds of winning a game than {user}.",
  "Every lobby {user} joins instantly becomes a 4v5.",
  "{user}'s greatest achievement is making everyone else look better by comparison.",
  "{user} is so lost in-game they need Google Maps.",
  "The only thing {user} tops is the death leaderboard.",
  "When {user} said 'I'm cracked', they meant their screen. From headbutting it.",
  "{user}'s in-game economy is as bad as their real one.",
  "Even training dummies dodge better than {user}.",
  "{user} treats respawn timers like a break. Because they see them so often.",
  "{user}'s gameplay footage is used in anti-gaming PSAs.",
  "They put {user} in a 1v1 against a tutorial bot and the bot tbag'd them.",
  "{user} is the human equivalent of a blue shell — only hurts their own team.",
  "The enemy team has {user}'s schedule memorized. Free wins on demand.",
];

export default {
  data: new SlashCommandBuilder()
    .setName('roast')
    .setDescription('Roast someone in the server')
    .addUserOption(option =>
      option
        .setName('target')
        .setDescription('The unlucky person to roast')
        .setRequired(true),
    ),
  async execute(interaction) {
    const target = interaction.options.getUser('target');
    const roast = roasts[Math.floor(Math.random() * roasts.length)];
    await interaction.reply(`🔥 ${roast.replace(/\{user\}/g, target.toString())}`);
  },
};
